### ISSUE TITLE
Registration Information

### ISSUE THREAD

**Issue by stdavis** [agrc/fiber-verification#4]
As a potential user of the application I want to have a way to register - entering my name, company, phone #, email, username, password so I can log in 

Success: I will see a registration button with boxes to type in the various required items, all listed items in the story would be required.

**Comment by stdavis** [comment]
@jpechmann: Do you still need a phone number for this?

**Comment by jpechmann** [comment]
I'm going to call it and say no.

**Comment by stdavis** [comment]
Thx
